apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: s2
  system: production
